# Generated by Django 5.1.2 on 2024-11-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_curso_disciplina"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curso",
            name="disciplina",
        ),
    ]
