# Generated by Django 5.1.2 on 2024-11-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_curso_disciplina"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curso",
            name="disciplina",
        ),
        migrations.AddField(
            model_name="curso",
            name="disciplina",
            field=models.ManyToManyField(blank=True, to="core.disciplina"),
        ),
    ]
