# Generated by Django 5.1.2 on 2024-11-28 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_curso_disciplina_curso_disciplina"),
    ]

    operations = [
        migrations.CreateModel(
            name="Turma",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("curso", models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to="core.curso")),
            ],
        ),
    ]
