# Generated by Django 5.1.2 on 2024-11-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_aluno"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="matricula",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
