# Generated by Django 5.1.2 on 2024-11-29 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_ano"),
    ]

    operations = [
        migrations.AddField(
            model_name="turma",
            name="ano",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.ano"),
        ),
    ]
