# Generated by Django 5.1.3 on 2024-11-29 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_aluno_capa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ocorrencia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assunto", models.CharField(max_length=300)),
                (
                    "papel_ocorrencia",
                    models.IntegerField(
                        choices=[(1, "Registrar Atraso"), (2, "Sem Uniforme"), (3, "Reunião NUPE")], default=1
                    ),
                ),
                ("aluno", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.aluno")),
            ],
        ),
    ]
