# Generated by Django 5.1.3 on 2024-11-29 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_ocorrencia"),
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocorrencia",
            name="assunto",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="ocorrencia",
            name="papel_ocorrencia",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Registrar Atraso"), (2, "Sem Uniforme"), (3, "Reunião NUPE")],
                default=1,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100, null=True)),
                ("cpf", models.CharField(max_length=11)),
                (
                    "capa",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="uploader.image",
                    ),
                ),
            ],
        ),
    ]
