# Generated by Django 5.1.3 on 2024-11-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_ocorrencia_assunto_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trimestre",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("periodo", models.CharField(max_length=20)),
            ],
        ),
    ]
