# Generated by Django 5.1.3 on 2024-11-29 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_trimestre"),
    ]

    operations = [
        migrations.AddField(
            model_name="trimestre",
            name="ano",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.ano"),
        ),
        migrations.CreateModel(
            name="Nota",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("disciplina", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.disciplina")),
                ("trimestre", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.trimestre")),
            ],
        ),
    ]
