# Generated by Django 5.1.3 on 2024-11-29 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_trimestre_ano_nota"),
    ]

    operations = [
        migrations.AddField(
            model_name="nota",
            name="aluno",
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to="core.aluno"),
            preserve_default=False,
        ),
    ]
