# Generated by Django 5.1.3 on 2024-11-30 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_nota_aluno"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trimestre",
            name="ano",
        ),
        migrations.RemoveField(
            model_name="turma",
            name="ano",
        ),
        migrations.RemoveField(
            model_name="nota",
            name="trimestre",
        ),
        migrations.AddField(
            model_name="nota",
            name="turma",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to="core.turma"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Ano",
        ),
        migrations.DeleteModel(
            name="Trimestre",
        ),
    ]
