# Generated by Django 5.1.3 on 2024-11-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_remove_trimestre_ano_remove_turma_ano_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nota",
            name="trimestre",
            field=models.IntegerField(
                choices=[(1, "1º Trimestre"), (2, "2º Trimestre"), (3, "3º Trimestre")], default=1
            ),
        ),
    ]
