# Generated by Django 5.1.3 on 2024-11-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_nota_trimestre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curso",
            name="disciplina",
        ),
        migrations.AddField(
            model_name="turma",
            name="disciplina",
            field=models.ManyToManyField(blank=True, to="core.disciplina"),
        ),
    ]
