# Generated by Django 5.1.3 on 2024-11-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_remove_curso_disciplina_turma_disciplina"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocorrencia",
            name="data_ocorrencia",
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name="ocorrencia",
            name="trimestre",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "1º Trimestre"), (2, "2º Trimestre"), (3, "3º Trimestre")],
                default=1,
                null=True,
            ),
        ),
    ]
