from .aluno import Aluno
from .ano import Ano
from .curso import Curso
from .disciplina import Disciplina
from .nota import Nota
from .ocorrencia import Ocorrencia
from .professor import Professor
from .trimestre import Trimestre
from .turma import Turma
from .user import User
